/****************************************************************************
 *
 *   Copyright (C) 2013-2016 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /home/intrepid/src1210_PixHawk2/Firmware/msg/battery_status.msg */


#include <px4_config.h>
#include <drivers/drv_orb_dev.h>
#include <microcdr/microCdr.h>
#include <uORB/topics/battery_status.h>

constexpr char __orb_battery_status_fields[] = "uint64_t timestamp;float voltage_v;float voltage_filtered_v;float current_a;float current_filtered_a;float discharged_mah;float remaining;float scale;int32_t cell_count;bool connected;bool system_source;uint8_t priority;uint8_t warning;uint8_t[4] _padding0;";

ORB_DEFINE(battery_status, struct battery_status_s, 44,
    __orb_battery_status_fields);



void serialize_battery_status(const struct battery_status_s *input, char *output, uint32_t *length, struct microCDR *microCDRWriter)
{
    if (nullptr == input || nullptr == output || nullptr == length || nullptr == microCDRWriter) return;

    resetStaticMicroCDRForSerialize(microCDRWriter);

	serializeFloat(input->voltage_v, microCDRWriter);
	serializeFloat(input->voltage_filtered_v, microCDRWriter);
	serializeFloat(input->current_a, microCDRWriter);
	serializeFloat(input->current_filtered_a, microCDRWriter);
	serializeFloat(input->discharged_mah, microCDRWriter);
	serializeFloat(input->remaining, microCDRWriter);
	serializeFloat(input->scale, microCDRWriter);
	serializeInt(input->cell_count, microCDRWriter);
	serializeBool(input->connected, microCDRWriter);
	serializeBool(input->system_source, microCDRWriter);
	serializeUnsignedChar(input->priority, microCDRWriter);
	serializeUnsignedChar(input->warning, microCDRWriter);


    (*length) = microCDRWriter->m_microBuffer->m_serializedBuffer;
}

void deserialize_battery_status(struct battery_status_s *output, char *input, struct microCDR *microCDRReader)
{
    if (nullptr == output || nullptr == input || nullptr == microCDRReader) return;

    resetStaticMicroCDRForDeserialize(microCDRReader);

	deserializeFloat(&output->voltage_v, microCDRReader);
	deserializeFloat(&output->voltage_filtered_v, microCDRReader);
	deserializeFloat(&output->current_a, microCDRReader);
	deserializeFloat(&output->current_filtered_a, microCDRReader);
	deserializeFloat(&output->discharged_mah, microCDRReader);
	deserializeFloat(&output->remaining, microCDRReader);
	deserializeFloat(&output->scale, microCDRReader);
	deserializeInt(&output->cell_count, microCDRReader);
	deserializeBool(&output->connected, microCDRReader);
	deserializeBool(&output->system_source, microCDRReader);
	deserializeUnsignedChar(&output->priority, microCDRReader);
	deserializeUnsignedChar(&output->warning, microCDRReader);

}