/****************************************************************************
 *
 *   Copyright (C) 2013-2016 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /home/intrepid/src1210_PixHawk2/Firmware/msg/collision_report.msg */


#include <px4_config.h>
#include <drivers/drv_orb_dev.h>
#include <microcdr/microCdr.h>
#include <uORB/topics/collision_report.h>

constexpr char __orb_collision_report_fields[] = "uint64_t timestamp;uint32_t id;float time_to_minimum_delta;float altitude_minimum_delta;float horizontal_minimum_delta;uint8_t src;uint8_t action;uint8_t threat_level;uint8_t[5] _padding0;";

ORB_DEFINE(collision_report, struct collision_report_s, 27,
    __orb_collision_report_fields);



void serialize_collision_report(const struct collision_report_s *input, char *output, uint32_t *length, struct microCDR *microCDRWriter)
{
    if (nullptr == input || nullptr == output || nullptr == length || nullptr == microCDRWriter) return;

    resetStaticMicroCDRForSerialize(microCDRWriter);

	serializeUnsignedInt(input->id, microCDRWriter);
	serializeFloat(input->time_to_minimum_delta, microCDRWriter);
	serializeFloat(input->altitude_minimum_delta, microCDRWriter);
	serializeFloat(input->horizontal_minimum_delta, microCDRWriter);
	serializeUnsignedChar(input->src, microCDRWriter);
	serializeUnsignedChar(input->action, microCDRWriter);
	serializeUnsignedChar(input->threat_level, microCDRWriter);


    (*length) = microCDRWriter->m_microBuffer->m_serializedBuffer;
}

void deserialize_collision_report(struct collision_report_s *output, char *input, struct microCDR *microCDRReader)
{
    if (nullptr == output || nullptr == input || nullptr == microCDRReader) return;

    resetStaticMicroCDRForDeserialize(microCDRReader);

	deserializeUnsignedInt(&output->id, microCDRReader);
	deserializeFloat(&output->time_to_minimum_delta, microCDRReader);
	deserializeFloat(&output->altitude_minimum_delta, microCDRReader);
	deserializeFloat(&output->horizontal_minimum_delta, microCDRReader);
	deserializeUnsignedChar(&output->src, microCDRReader);
	deserializeUnsignedChar(&output->action, microCDRReader);
	deserializeUnsignedChar(&output->threat_level, microCDRReader);

}