/****************************************************************************
 *
 *   Copyright (C) 2013-2016 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /home/intrepid/src1210_PixHawk2/Firmware/msg/ekf2_innovations.msg */


#include <px4_config.h>
#include <drivers/drv_orb_dev.h>
#include <microcdr/microCdr.h>
#include <uORB/topics/ekf2_innovations.h>

constexpr char __orb_ekf2_innovations_fields[] = "uint64_t timestamp;float[6] vel_pos_innov;float[3] mag_innov;float heading_innov;float airspeed_innov;float beta_innov;float[2] flow_innov;float hagl_innov;float[6] vel_pos_innov_var;float[3] mag_innov_var;float heading_innov_var;float airspeed_innov_var;float beta_innov_var;float[2] flow_innov_var;float hagl_innov_var;float[3] output_tracking_error;float[2] drag_innov;float[2] drag_innov_var;uint8_t[4] _padding0;";

ORB_DEFINE(ekf2_innovations, struct ekf2_innovations_s, 156,
    __orb_ekf2_innovations_fields);



void serialize_ekf2_innovations(const struct ekf2_innovations_s *input, char *output, uint32_t *length, struct microCDR *microCDRWriter)
{
    if (nullptr == input || nullptr == output || nullptr == length || nullptr == microCDRWriter) return;

    resetStaticMicroCDRForSerialize(microCDRWriter);

	serializeFloatArray(input->vel_pos_innov, 6, microCDRWriter);
	serializeFloatArray(input->mag_innov, 3, microCDRWriter);
	serializeFloat(input->heading_innov, microCDRWriter);
	serializeFloat(input->airspeed_innov, microCDRWriter);
	serializeFloat(input->beta_innov, microCDRWriter);
	serializeFloatArray(input->flow_innov, 2, microCDRWriter);
	serializeFloat(input->hagl_innov, microCDRWriter);
	serializeFloatArray(input->vel_pos_innov_var, 6, microCDRWriter);
	serializeFloatArray(input->mag_innov_var, 3, microCDRWriter);
	serializeFloat(input->heading_innov_var, microCDRWriter);
	serializeFloat(input->airspeed_innov_var, microCDRWriter);
	serializeFloat(input->beta_innov_var, microCDRWriter);
	serializeFloatArray(input->flow_innov_var, 2, microCDRWriter);
	serializeFloat(input->hagl_innov_var, microCDRWriter);
	serializeFloatArray(input->output_tracking_error, 3, microCDRWriter);
	serializeFloatArray(input->drag_innov, 2, microCDRWriter);
	serializeFloatArray(input->drag_innov_var, 2, microCDRWriter);


    (*length) = microCDRWriter->m_microBuffer->m_serializedBuffer;
}

void deserialize_ekf2_innovations(struct ekf2_innovations_s *output, char *input, struct microCDR *microCDRReader)
{
    if (nullptr == output || nullptr == input || nullptr == microCDRReader) return;

    resetStaticMicroCDRForDeserialize(microCDRReader);

	deserializeFloat(&output->vel_pos_innov[0], microCDRReader);
	deserializeFloat(&output->vel_pos_innov[1], microCDRReader);
	deserializeFloat(&output->vel_pos_innov[2], microCDRReader);
	deserializeFloat(&output->vel_pos_innov[3], microCDRReader);
	deserializeFloat(&output->vel_pos_innov[4], microCDRReader);
	deserializeFloat(&output->vel_pos_innov[5], microCDRReader);
	deserializeFloat(&output->mag_innov[0], microCDRReader);
	deserializeFloat(&output->mag_innov[1], microCDRReader);
	deserializeFloat(&output->mag_innov[2], microCDRReader);
	deserializeFloat(&output->heading_innov, microCDRReader);
	deserializeFloat(&output->airspeed_innov, microCDRReader);
	deserializeFloat(&output->beta_innov, microCDRReader);
	deserializeFloat(&output->flow_innov[0], microCDRReader);
	deserializeFloat(&output->flow_innov[1], microCDRReader);
	deserializeFloat(&output->hagl_innov, microCDRReader);
	deserializeFloat(&output->vel_pos_innov_var[0], microCDRReader);
	deserializeFloat(&output->vel_pos_innov_var[1], microCDRReader);
	deserializeFloat(&output->vel_pos_innov_var[2], microCDRReader);
	deserializeFloat(&output->vel_pos_innov_var[3], microCDRReader);
	deserializeFloat(&output->vel_pos_innov_var[4], microCDRReader);
	deserializeFloat(&output->vel_pos_innov_var[5], microCDRReader);
	deserializeFloat(&output->mag_innov_var[0], microCDRReader);
	deserializeFloat(&output->mag_innov_var[1], microCDRReader);
	deserializeFloat(&output->mag_innov_var[2], microCDRReader);
	deserializeFloat(&output->heading_innov_var, microCDRReader);
	deserializeFloat(&output->airspeed_innov_var, microCDRReader);
	deserializeFloat(&output->beta_innov_var, microCDRReader);
	deserializeFloat(&output->flow_innov_var[0], microCDRReader);
	deserializeFloat(&output->flow_innov_var[1], microCDRReader);
	deserializeFloat(&output->hagl_innov_var, microCDRReader);
	deserializeFloat(&output->output_tracking_error[0], microCDRReader);
	deserializeFloat(&output->output_tracking_error[1], microCDRReader);
	deserializeFloat(&output->output_tracking_error[2], microCDRReader);
	deserializeFloat(&output->drag_innov[0], microCDRReader);
	deserializeFloat(&output->drag_innov[1], microCDRReader);
	deserializeFloat(&output->drag_innov_var[0], microCDRReader);
	deserializeFloat(&output->drag_innov_var[1], microCDRReader);

}