/****************************************************************************
 *
 *   Copyright (C) 2013-2016 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /home/intrepid/src1210_PixHawk2/Firmware/msg/esc_status.msg */


#include <px4_config.h>
#include <drivers/drv_orb_dev.h>
#include <microcdr/microCdr.h>
#include <uORB/topics/esc_status.h>

constexpr char __orb_esc_status_fields[] = "uint64_t timestamp;uint16_t counter;uint8_t esc_count;uint8_t esc_connectiontype;uint8_t[4] _padding0;esc_report[8] esc;";

ORB_DEFINE(esc_status, struct esc_status_s, 400,
    __orb_esc_status_fields);



void serialize_esc_status(const struct esc_status_s *input, char *output, uint32_t *length, struct microCDR *microCDRWriter)
{
    if (nullptr == input || nullptr == output || nullptr == length || nullptr == microCDRWriter) return;

    resetStaticMicroCDRForSerialize(microCDRWriter);

	serializeUnsignedShort(input->counter, microCDRWriter);
	serializeUnsignedChar(input->esc_count, microCDRWriter);
	serializeUnsignedChar(input->esc_connectiontype, microCDRWriter);
	serializeUnsignedInt(input->esc[0].esc_errorcount, microCDRWriter);
	serializeInt(input->esc[0].esc_rpm, microCDRWriter);
	serializeFloat(input->esc[0].esc_voltage, microCDRWriter);
	serializeFloat(input->esc[0].esc_current, microCDRWriter);
	serializeFloat(input->esc[0].esc_temperature, microCDRWriter);
	serializeFloat(input->esc[0].esc_setpoint, microCDRWriter);
	serializeUnsignedShort(input->esc[0].esc_setpoint_raw, microCDRWriter);
	serializeUnsignedShort(input->esc[0].esc_address, microCDRWriter);
	serializeUnsignedShort(input->esc[0].esc_version, microCDRWriter);
	serializeUnsignedShort(input->esc[0].esc_state, microCDRWriter);
	serializeUnsignedChar(input->esc[0].esc_vendor, microCDRWriter);
	serializeUnsignedInt(input->esc[1].esc_errorcount, microCDRWriter);
	serializeInt(input->esc[1].esc_rpm, microCDRWriter);
	serializeFloat(input->esc[1].esc_voltage, microCDRWriter);
	serializeFloat(input->esc[1].esc_current, microCDRWriter);
	serializeFloat(input->esc[1].esc_temperature, microCDRWriter);
	serializeFloat(input->esc[1].esc_setpoint, microCDRWriter);
	serializeUnsignedShort(input->esc[1].esc_setpoint_raw, microCDRWriter);
	serializeUnsignedShort(input->esc[1].esc_address, microCDRWriter);
	serializeUnsignedShort(input->esc[1].esc_version, microCDRWriter);
	serializeUnsignedShort(input->esc[1].esc_state, microCDRWriter);
	serializeUnsignedChar(input->esc[1].esc_vendor, microCDRWriter);
	serializeUnsignedInt(input->esc[2].esc_errorcount, microCDRWriter);
	serializeInt(input->esc[2].esc_rpm, microCDRWriter);
	serializeFloat(input->esc[2].esc_voltage, microCDRWriter);
	serializeFloat(input->esc[2].esc_current, microCDRWriter);
	serializeFloat(input->esc[2].esc_temperature, microCDRWriter);
	serializeFloat(input->esc[2].esc_setpoint, microCDRWriter);
	serializeUnsignedShort(input->esc[2].esc_setpoint_raw, microCDRWriter);
	serializeUnsignedShort(input->esc[2].esc_address, microCDRWriter);
	serializeUnsignedShort(input->esc[2].esc_version, microCDRWriter);
	serializeUnsignedShort(input->esc[2].esc_state, microCDRWriter);
	serializeUnsignedChar(input->esc[2].esc_vendor, microCDRWriter);
	serializeUnsignedInt(input->esc[3].esc_errorcount, microCDRWriter);
	serializeInt(input->esc[3].esc_rpm, microCDRWriter);
	serializeFloat(input->esc[3].esc_voltage, microCDRWriter);
	serializeFloat(input->esc[3].esc_current, microCDRWriter);
	serializeFloat(input->esc[3].esc_temperature, microCDRWriter);
	serializeFloat(input->esc[3].esc_setpoint, microCDRWriter);
	serializeUnsignedShort(input->esc[3].esc_setpoint_raw, microCDRWriter);
	serializeUnsignedShort(input->esc[3].esc_address, microCDRWriter);
	serializeUnsignedShort(input->esc[3].esc_version, microCDRWriter);
	serializeUnsignedShort(input->esc[3].esc_state, microCDRWriter);
	serializeUnsignedChar(input->esc[3].esc_vendor, microCDRWriter);
	serializeUnsignedInt(input->esc[4].esc_errorcount, microCDRWriter);
	serializeInt(input->esc[4].esc_rpm, microCDRWriter);
	serializeFloat(input->esc[4].esc_voltage, microCDRWriter);
	serializeFloat(input->esc[4].esc_current, microCDRWriter);
	serializeFloat(input->esc[4].esc_temperature, microCDRWriter);
	serializeFloat(input->esc[4].esc_setpoint, microCDRWriter);
	serializeUnsignedShort(input->esc[4].esc_setpoint_raw, microCDRWriter);
	serializeUnsignedShort(input->esc[4].esc_address, microCDRWriter);
	serializeUnsignedShort(input->esc[4].esc_version, microCDRWriter);
	serializeUnsignedShort(input->esc[4].esc_state, microCDRWriter);
	serializeUnsignedChar(input->esc[4].esc_vendor, microCDRWriter);
	serializeUnsignedInt(input->esc[5].esc_errorcount, microCDRWriter);
	serializeInt(input->esc[5].esc_rpm, microCDRWriter);
	serializeFloat(input->esc[5].esc_voltage, microCDRWriter);
	serializeFloat(input->esc[5].esc_current, microCDRWriter);
	serializeFloat(input->esc[5].esc_temperature, microCDRWriter);
	serializeFloat(input->esc[5].esc_setpoint, microCDRWriter);
	serializeUnsignedShort(input->esc[5].esc_setpoint_raw, microCDRWriter);
	serializeUnsignedShort(input->esc[5].esc_address, microCDRWriter);
	serializeUnsignedShort(input->esc[5].esc_version, microCDRWriter);
	serializeUnsignedShort(input->esc[5].esc_state, microCDRWriter);
	serializeUnsignedChar(input->esc[5].esc_vendor, microCDRWriter);
	serializeUnsignedInt(input->esc[6].esc_errorcount, microCDRWriter);
	serializeInt(input->esc[6].esc_rpm, microCDRWriter);
	serializeFloat(input->esc[6].esc_voltage, microCDRWriter);
	serializeFloat(input->esc[6].esc_current, microCDRWriter);
	serializeFloat(input->esc[6].esc_temperature, microCDRWriter);
	serializeFloat(input->esc[6].esc_setpoint, microCDRWriter);
	serializeUnsignedShort(input->esc[6].esc_setpoint_raw, microCDRWriter);
	serializeUnsignedShort(input->esc[6].esc_address, microCDRWriter);
	serializeUnsignedShort(input->esc[6].esc_version, microCDRWriter);
	serializeUnsignedShort(input->esc[6].esc_state, microCDRWriter);
	serializeUnsignedChar(input->esc[6].esc_vendor, microCDRWriter);
	serializeUnsignedInt(input->esc[7].esc_errorcount, microCDRWriter);
	serializeInt(input->esc[7].esc_rpm, microCDRWriter);
	serializeFloat(input->esc[7].esc_voltage, microCDRWriter);
	serializeFloat(input->esc[7].esc_current, microCDRWriter);
	serializeFloat(input->esc[7].esc_temperature, microCDRWriter);
	serializeFloat(input->esc[7].esc_setpoint, microCDRWriter);
	serializeUnsignedShort(input->esc[7].esc_setpoint_raw, microCDRWriter);
	serializeUnsignedShort(input->esc[7].esc_address, microCDRWriter);
	serializeUnsignedShort(input->esc[7].esc_version, microCDRWriter);
	serializeUnsignedShort(input->esc[7].esc_state, microCDRWriter);
	serializeUnsignedChar(input->esc[7].esc_vendor, microCDRWriter);


    (*length) = microCDRWriter->m_microBuffer->m_serializedBuffer;
}

void deserialize_esc_status(struct esc_status_s *output, char *input, struct microCDR *microCDRReader)
{
    if (nullptr == output || nullptr == input || nullptr == microCDRReader) return;

    resetStaticMicroCDRForDeserialize(microCDRReader);

	deserializeUnsignedShort(&output->counter, microCDRReader);
	deserializeUnsignedChar(&output->esc_count, microCDRReader);
	deserializeUnsignedChar(&output->esc_connectiontype, microCDRReader);
	deserializeUnsignedInt(&output->esc[0].esc_errorcount, microCDRReader);
	deserializeInt(&output->esc[0].esc_rpm, microCDRReader);
	deserializeFloat(&output->esc[0].esc_voltage, microCDRReader);
	deserializeFloat(&output->esc[0].esc_current, microCDRReader);
	deserializeFloat(&output->esc[0].esc_temperature, microCDRReader);
	deserializeFloat(&output->esc[0].esc_setpoint, microCDRReader);
	deserializeUnsignedShort(&output->esc[0].esc_setpoint_raw, microCDRReader);
	deserializeUnsignedShort(&output->esc[0].esc_address, microCDRReader);
	deserializeUnsignedShort(&output->esc[0].esc_version, microCDRReader);
	deserializeUnsignedShort(&output->esc[0].esc_state, microCDRReader);
	deserializeUnsignedChar(&output->esc[0].esc_vendor, microCDRReader);
	deserializeUnsignedInt(&output->esc[1].esc_errorcount, microCDRReader);
	deserializeInt(&output->esc[1].esc_rpm, microCDRReader);
	deserializeFloat(&output->esc[1].esc_voltage, microCDRReader);
	deserializeFloat(&output->esc[1].esc_current, microCDRReader);
	deserializeFloat(&output->esc[1].esc_temperature, microCDRReader);
	deserializeFloat(&output->esc[1].esc_setpoint, microCDRReader);
	deserializeUnsignedShort(&output->esc[1].esc_setpoint_raw, microCDRReader);
	deserializeUnsignedShort(&output->esc[1].esc_address, microCDRReader);
	deserializeUnsignedShort(&output->esc[1].esc_version, microCDRReader);
	deserializeUnsignedShort(&output->esc[1].esc_state, microCDRReader);
	deserializeUnsignedChar(&output->esc[1].esc_vendor, microCDRReader);
	deserializeUnsignedInt(&output->esc[2].esc_errorcount, microCDRReader);
	deserializeInt(&output->esc[2].esc_rpm, microCDRReader);
	deserializeFloat(&output->esc[2].esc_voltage, microCDRReader);
	deserializeFloat(&output->esc[2].esc_current, microCDRReader);
	deserializeFloat(&output->esc[2].esc_temperature, microCDRReader);
	deserializeFloat(&output->esc[2].esc_setpoint, microCDRReader);
	deserializeUnsignedShort(&output->esc[2].esc_setpoint_raw, microCDRReader);
	deserializeUnsignedShort(&output->esc[2].esc_address, microCDRReader);
	deserializeUnsignedShort(&output->esc[2].esc_version, microCDRReader);
	deserializeUnsignedShort(&output->esc[2].esc_state, microCDRReader);
	deserializeUnsignedChar(&output->esc[2].esc_vendor, microCDRReader);
	deserializeUnsignedInt(&output->esc[3].esc_errorcount, microCDRReader);
	deserializeInt(&output->esc[3].esc_rpm, microCDRReader);
	deserializeFloat(&output->esc[3].esc_voltage, microCDRReader);
	deserializeFloat(&output->esc[3].esc_current, microCDRReader);
	deserializeFloat(&output->esc[3].esc_temperature, microCDRReader);
	deserializeFloat(&output->esc[3].esc_setpoint, microCDRReader);
	deserializeUnsignedShort(&output->esc[3].esc_setpoint_raw, microCDRReader);
	deserializeUnsignedShort(&output->esc[3].esc_address, microCDRReader);
	deserializeUnsignedShort(&output->esc[3].esc_version, microCDRReader);
	deserializeUnsignedShort(&output->esc[3].esc_state, microCDRReader);
	deserializeUnsignedChar(&output->esc[3].esc_vendor, microCDRReader);
	deserializeUnsignedInt(&output->esc[4].esc_errorcount, microCDRReader);
	deserializeInt(&output->esc[4].esc_rpm, microCDRReader);
	deserializeFloat(&output->esc[4].esc_voltage, microCDRReader);
	deserializeFloat(&output->esc[4].esc_current, microCDRReader);
	deserializeFloat(&output->esc[4].esc_temperature, microCDRReader);
	deserializeFloat(&output->esc[4].esc_setpoint, microCDRReader);
	deserializeUnsignedShort(&output->esc[4].esc_setpoint_raw, microCDRReader);
	deserializeUnsignedShort(&output->esc[4].esc_address, microCDRReader);
	deserializeUnsignedShort(&output->esc[4].esc_version, microCDRReader);
	deserializeUnsignedShort(&output->esc[4].esc_state, microCDRReader);
	deserializeUnsignedChar(&output->esc[4].esc_vendor, microCDRReader);
	deserializeUnsignedInt(&output->esc[5].esc_errorcount, microCDRReader);
	deserializeInt(&output->esc[5].esc_rpm, microCDRReader);
	deserializeFloat(&output->esc[5].esc_voltage, microCDRReader);
	deserializeFloat(&output->esc[5].esc_current, microCDRReader);
	deserializeFloat(&output->esc[5].esc_temperature, microCDRReader);
	deserializeFloat(&output->esc[5].esc_setpoint, microCDRReader);
	deserializeUnsignedShort(&output->esc[5].esc_setpoint_raw, microCDRReader);
	deserializeUnsignedShort(&output->esc[5].esc_address, microCDRReader);
	deserializeUnsignedShort(&output->esc[5].esc_version, microCDRReader);
	deserializeUnsignedShort(&output->esc[5].esc_state, microCDRReader);
	deserializeUnsignedChar(&output->esc[5].esc_vendor, microCDRReader);
	deserializeUnsignedInt(&output->esc[6].esc_errorcount, microCDRReader);
	deserializeInt(&output->esc[6].esc_rpm, microCDRReader);
	deserializeFloat(&output->esc[6].esc_voltage, microCDRReader);
	deserializeFloat(&output->esc[6].esc_current, microCDRReader);
	deserializeFloat(&output->esc[6].esc_temperature, microCDRReader);
	deserializeFloat(&output->esc[6].esc_setpoint, microCDRReader);
	deserializeUnsignedShort(&output->esc[6].esc_setpoint_raw, microCDRReader);
	deserializeUnsignedShort(&output->esc[6].esc_address, microCDRReader);
	deserializeUnsignedShort(&output->esc[6].esc_version, microCDRReader);
	deserializeUnsignedShort(&output->esc[6].esc_state, microCDRReader);
	deserializeUnsignedChar(&output->esc[6].esc_vendor, microCDRReader);
	deserializeUnsignedInt(&output->esc[7].esc_errorcount, microCDRReader);
	deserializeInt(&output->esc[7].esc_rpm, microCDRReader);
	deserializeFloat(&output->esc[7].esc_voltage, microCDRReader);
	deserializeFloat(&output->esc[7].esc_current, microCDRReader);
	deserializeFloat(&output->esc[7].esc_temperature, microCDRReader);
	deserializeFloat(&output->esc[7].esc_setpoint, microCDRReader);
	deserializeUnsignedShort(&output->esc[7].esc_setpoint_raw, microCDRReader);
	deserializeUnsignedShort(&output->esc[7].esc_address, microCDRReader);
	deserializeUnsignedShort(&output->esc[7].esc_version, microCDRReader);
	deserializeUnsignedShort(&output->esc[7].esc_state, microCDRReader);
	deserializeUnsignedChar(&output->esc[7].esc_vendor, microCDRReader);

}