/****************************************************************************
 *
 *   Copyright (C) 2013-2016 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /home/intrepid/src1210_PixHawk2/Firmware/msg/mavlink_log.msg */


#include <px4_config.h>
#include <drivers/drv_orb_dev.h>
#include <microcdr/microCdr.h>
#include <uORB/topics/mavlink_log.h>

constexpr char __orb_mavlink_log_fields[] = "uint64_t timestamp;uint8_t[50] text;uint8_t severity;uint8_t[5] _padding0;";

ORB_DEFINE(mavlink_log, struct mavlink_log_s, 59,
    __orb_mavlink_log_fields);



void serialize_mavlink_log(const struct mavlink_log_s *input, char *output, uint32_t *length, struct microCDR *microCDRWriter)
{
    if (nullptr == input || nullptr == output || nullptr == length || nullptr == microCDRWriter) return;

    resetStaticMicroCDRForSerialize(microCDRWriter);

	serializeUnsignedCharArray(input->text, 50, microCDRWriter);
	serializeUnsignedChar(input->severity, microCDRWriter);


    (*length) = microCDRWriter->m_microBuffer->m_serializedBuffer;
}

void deserialize_mavlink_log(struct mavlink_log_s *output, char *input, struct microCDR *microCDRReader)
{
    if (nullptr == output || nullptr == input || nullptr == microCDRReader) return;

    resetStaticMicroCDRForDeserialize(microCDRReader);

	deserializeUnsignedChar(&output->text[0], microCDRReader);
	deserializeUnsignedChar(&output->text[1], microCDRReader);
	deserializeUnsignedChar(&output->text[2], microCDRReader);
	deserializeUnsignedChar(&output->text[3], microCDRReader);
	deserializeUnsignedChar(&output->text[4], microCDRReader);
	deserializeUnsignedChar(&output->text[5], microCDRReader);
	deserializeUnsignedChar(&output->text[6], microCDRReader);
	deserializeUnsignedChar(&output->text[7], microCDRReader);
	deserializeUnsignedChar(&output->text[8], microCDRReader);
	deserializeUnsignedChar(&output->text[9], microCDRReader);
	deserializeUnsignedChar(&output->text[10], microCDRReader);
	deserializeUnsignedChar(&output->text[11], microCDRReader);
	deserializeUnsignedChar(&output->text[12], microCDRReader);
	deserializeUnsignedChar(&output->text[13], microCDRReader);
	deserializeUnsignedChar(&output->text[14], microCDRReader);
	deserializeUnsignedChar(&output->text[15], microCDRReader);
	deserializeUnsignedChar(&output->text[16], microCDRReader);
	deserializeUnsignedChar(&output->text[17], microCDRReader);
	deserializeUnsignedChar(&output->text[18], microCDRReader);
	deserializeUnsignedChar(&output->text[19], microCDRReader);
	deserializeUnsignedChar(&output->text[20], microCDRReader);
	deserializeUnsignedChar(&output->text[21], microCDRReader);
	deserializeUnsignedChar(&output->text[22], microCDRReader);
	deserializeUnsignedChar(&output->text[23], microCDRReader);
	deserializeUnsignedChar(&output->text[24], microCDRReader);
	deserializeUnsignedChar(&output->text[25], microCDRReader);
	deserializeUnsignedChar(&output->text[26], microCDRReader);
	deserializeUnsignedChar(&output->text[27], microCDRReader);
	deserializeUnsignedChar(&output->text[28], microCDRReader);
	deserializeUnsignedChar(&output->text[29], microCDRReader);
	deserializeUnsignedChar(&output->text[30], microCDRReader);
	deserializeUnsignedChar(&output->text[31], microCDRReader);
	deserializeUnsignedChar(&output->text[32], microCDRReader);
	deserializeUnsignedChar(&output->text[33], microCDRReader);
	deserializeUnsignedChar(&output->text[34], microCDRReader);
	deserializeUnsignedChar(&output->text[35], microCDRReader);
	deserializeUnsignedChar(&output->text[36], microCDRReader);
	deserializeUnsignedChar(&output->text[37], microCDRReader);
	deserializeUnsignedChar(&output->text[38], microCDRReader);
	deserializeUnsignedChar(&output->text[39], microCDRReader);
	deserializeUnsignedChar(&output->text[40], microCDRReader);
	deserializeUnsignedChar(&output->text[41], microCDRReader);
	deserializeUnsignedChar(&output->text[42], microCDRReader);
	deserializeUnsignedChar(&output->text[43], microCDRReader);
	deserializeUnsignedChar(&output->text[44], microCDRReader);
	deserializeUnsignedChar(&output->text[45], microCDRReader);
	deserializeUnsignedChar(&output->text[46], microCDRReader);
	deserializeUnsignedChar(&output->text[47], microCDRReader);
	deserializeUnsignedChar(&output->text[48], microCDRReader);
	deserializeUnsignedChar(&output->text[49], microCDRReader);
	deserializeUnsignedChar(&output->severity, microCDRReader);

}