/****************************************************************************
 *
 *   Copyright (C) 2013-2016 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /home/intrepid/src1210_PixHawk2/Firmware/msg/system_power.msg */


#include <px4_config.h>
#include <drivers/drv_orb_dev.h>
#include <microcdr/microCdr.h>
#include <uORB/topics/system_power.h>

constexpr char __orb_system_power_fields[] = "uint64_t timestamp;float voltage5V_v;float voltage3V3_v;uint8_t v3v3_valid;uint8_t usb_connected;uint8_t brick_valid;uint8_t usb_vaild;uint8_t servo_valid;uint8_t periph_5V_OC;uint8_t hipower_5V_OC;uint8_t[1] _padding0;";

ORB_DEFINE(system_power, struct system_power_s, 23,
    __orb_system_power_fields);



void serialize_system_power(const struct system_power_s *input, char *output, uint32_t *length, struct microCDR *microCDRWriter)
{
    if (nullptr == input || nullptr == output || nullptr == length || nullptr == microCDRWriter) return;

    resetStaticMicroCDRForSerialize(microCDRWriter);

	serializeFloat(input->voltage5V_v, microCDRWriter);
	serializeFloat(input->voltage3V3_v, microCDRWriter);
	serializeUnsignedChar(input->v3v3_valid, microCDRWriter);
	serializeUnsignedChar(input->usb_connected, microCDRWriter);
	serializeUnsignedChar(input->brick_valid, microCDRWriter);
	serializeUnsignedChar(input->usb_vaild, microCDRWriter);
	serializeUnsignedChar(input->servo_valid, microCDRWriter);
	serializeUnsignedChar(input->periph_5V_OC, microCDRWriter);
	serializeUnsignedChar(input->hipower_5V_OC, microCDRWriter);


    (*length) = microCDRWriter->m_microBuffer->m_serializedBuffer;
}

void deserialize_system_power(struct system_power_s *output, char *input, struct microCDR *microCDRReader)
{
    if (nullptr == output || nullptr == input || nullptr == microCDRReader) return;

    resetStaticMicroCDRForDeserialize(microCDRReader);

	deserializeFloat(&output->voltage5V_v, microCDRReader);
	deserializeFloat(&output->voltage3V3_v, microCDRReader);
	deserializeUnsignedChar(&output->v3v3_valid, microCDRReader);
	deserializeUnsignedChar(&output->usb_connected, microCDRReader);
	deserializeUnsignedChar(&output->brick_valid, microCDRReader);
	deserializeUnsignedChar(&output->usb_vaild, microCDRReader);
	deserializeUnsignedChar(&output->servo_valid, microCDRReader);
	deserializeUnsignedChar(&output->periph_5V_OC, microCDRReader);
	deserializeUnsignedChar(&output->hipower_5V_OC, microCDRReader);

}