/****************************************************************************
 *
 *   Copyright (C) 2013-2016 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /home/intrepid/src1210_PixHawk2/Firmware/msg/actuator_direct.msg */


#include <px4_config.h>
#include <drivers/drv_orb_dev.h>
#include <microcdr/microCdr.h>
#include <uORB/topics/actuator_direct.h>

constexpr char __orb_actuator_direct_fields[] = "uint64_t timestamp;uint32_t nvalues;float[16] values;uint8_t[4] _padding0;";

ORB_DEFINE(actuator_direct, struct actuator_direct_s, 76,
    __orb_actuator_direct_fields);



void serialize_actuator_direct(const struct actuator_direct_s *input, char *output, uint32_t *length, struct microCDR *microCDRWriter)
{
    if (nullptr == input || nullptr == output || nullptr == length || nullptr == microCDRWriter) return;

    resetStaticMicroCDRForSerialize(microCDRWriter);

	serializeUnsignedInt(input->nvalues, microCDRWriter);
	serializeFloatArray(input->values, 16, microCDRWriter);


    (*length) = microCDRWriter->m_microBuffer->m_serializedBuffer;
}

void deserialize_actuator_direct(struct actuator_direct_s *output, char *input, struct microCDR *microCDRReader)
{
    if (nullptr == output || nullptr == input || nullptr == microCDRReader) return;

    resetStaticMicroCDRForDeserialize(microCDRReader);

	deserializeUnsignedInt(&output->nvalues, microCDRReader);
	deserializeFloat(&output->values[0], microCDRReader);
	deserializeFloat(&output->values[1], microCDRReader);
	deserializeFloat(&output->values[2], microCDRReader);
	deserializeFloat(&output->values[3], microCDRReader);
	deserializeFloat(&output->values[4], microCDRReader);
	deserializeFloat(&output->values[5], microCDRReader);
	deserializeFloat(&output->values[6], microCDRReader);
	deserializeFloat(&output->values[7], microCDRReader);
	deserializeFloat(&output->values[8], microCDRReader);
	deserializeFloat(&output->values[9], microCDRReader);
	deserializeFloat(&output->values[10], microCDRReader);
	deserializeFloat(&output->values[11], microCDRReader);
	deserializeFloat(&output->values[12], microCDRReader);
	deserializeFloat(&output->values[13], microCDRReader);
	deserializeFloat(&output->values[14], microCDRReader);
	deserializeFloat(&output->values[15], microCDRReader);

}