/****************************************************************************
 *
 *   Copyright (C) 2013-2016 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /home/intrepid/src1210_PixHawk2/Firmware/msg/fw_pos_ctrl_status.msg */


#include <px4_config.h>
#include <drivers/drv_orb_dev.h>
#include <microcdr/microCdr.h>
#include <uORB/topics/fw_pos_ctrl_status.h>

constexpr char __orb_fw_pos_ctrl_status_fields[] = "uint64_t timestamp;float nav_roll;float nav_pitch;float nav_bearing;float target_bearing;float wp_dist;float xtrack_error;float turn_distance;float landing_horizontal_slope_displacement;float landing_slope_angle_rad;float landing_flare_length;bool abort_landing;uint8_t[7] _padding0;";

ORB_DEFINE(fw_pos_ctrl_status, struct fw_pos_ctrl_status_s, 49,
    __orb_fw_pos_ctrl_status_fields);



void serialize_fw_pos_ctrl_status(const struct fw_pos_ctrl_status_s *input, char *output, uint32_t *length, struct microCDR *microCDRWriter)
{
    if (nullptr == input || nullptr == output || nullptr == length || nullptr == microCDRWriter) return;

    resetStaticMicroCDRForSerialize(microCDRWriter);

	serializeFloat(input->nav_roll, microCDRWriter);
	serializeFloat(input->nav_pitch, microCDRWriter);
	serializeFloat(input->nav_bearing, microCDRWriter);
	serializeFloat(input->target_bearing, microCDRWriter);
	serializeFloat(input->wp_dist, microCDRWriter);
	serializeFloat(input->xtrack_error, microCDRWriter);
	serializeFloat(input->turn_distance, microCDRWriter);
	serializeFloat(input->landing_horizontal_slope_displacement, microCDRWriter);
	serializeFloat(input->landing_slope_angle_rad, microCDRWriter);
	serializeFloat(input->landing_flare_length, microCDRWriter);
	serializeBool(input->abort_landing, microCDRWriter);


    (*length) = microCDRWriter->m_microBuffer->m_serializedBuffer;
}

void deserialize_fw_pos_ctrl_status(struct fw_pos_ctrl_status_s *output, char *input, struct microCDR *microCDRReader)
{
    if (nullptr == output || nullptr == input || nullptr == microCDRReader) return;

    resetStaticMicroCDRForDeserialize(microCDRReader);

	deserializeFloat(&output->nav_roll, microCDRReader);
	deserializeFloat(&output->nav_pitch, microCDRReader);
	deserializeFloat(&output->nav_bearing, microCDRReader);
	deserializeFloat(&output->target_bearing, microCDRReader);
	deserializeFloat(&output->wp_dist, microCDRReader);
	deserializeFloat(&output->xtrack_error, microCDRReader);
	deserializeFloat(&output->turn_distance, microCDRReader);
	deserializeFloat(&output->landing_horizontal_slope_displacement, microCDRReader);
	deserializeFloat(&output->landing_slope_angle_rad, microCDRReader);
	deserializeFloat(&output->landing_flare_length, microCDRReader);
	deserializeBool(&output->abort_landing, microCDRReader);

}