/****************************************************************************
 *
 *   Copyright (C) 2013-2016 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /home/intrepid/src1210_PixHawk2/Firmware/msg/offboard_control_mode.msg */


#include <px4_config.h>
#include <drivers/drv_orb_dev.h>
#include <microcdr/microCdr.h>
#include <uORB/topics/offboard_control_mode.h>

constexpr char __orb_offboard_control_mode_fields[] = "uint64_t timestamp;bool ignore_thrust;bool ignore_attitude;bool ignore_bodyrate;bool ignore_position;bool ignore_velocity;bool ignore_acceleration_force;bool ignore_alt_hold;uint8_t[1] _padding0;";

ORB_DEFINE(offboard_control_mode, struct offboard_control_mode_s, 15,
    __orb_offboard_control_mode_fields);



void serialize_offboard_control_mode(const struct offboard_control_mode_s *input, char *output, uint32_t *length, struct microCDR *microCDRWriter)
{
    if (nullptr == input || nullptr == output || nullptr == length || nullptr == microCDRWriter) return;

    resetStaticMicroCDRForSerialize(microCDRWriter);

	serializeBool(input->ignore_thrust, microCDRWriter);
	serializeBool(input->ignore_attitude, microCDRWriter);
	serializeBool(input->ignore_bodyrate, microCDRWriter);
	serializeBool(input->ignore_position, microCDRWriter);
	serializeBool(input->ignore_velocity, microCDRWriter);
	serializeBool(input->ignore_acceleration_force, microCDRWriter);
	serializeBool(input->ignore_alt_hold, microCDRWriter);


    (*length) = microCDRWriter->m_microBuffer->m_serializedBuffer;
}

void deserialize_offboard_control_mode(struct offboard_control_mode_s *output, char *input, struct microCDR *microCDRReader)
{
    if (nullptr == output || nullptr == input || nullptr == microCDRReader) return;

    resetStaticMicroCDRForDeserialize(microCDRReader);

	deserializeBool(&output->ignore_thrust, microCDRReader);
	deserializeBool(&output->ignore_attitude, microCDRReader);
	deserializeBool(&output->ignore_bodyrate, microCDRReader);
	deserializeBool(&output->ignore_position, microCDRReader);
	deserializeBool(&output->ignore_velocity, microCDRReader);
	deserializeBool(&output->ignore_acceleration_force, microCDRReader);
	deserializeBool(&output->ignore_alt_hold, microCDRReader);

}