/****************************************************************************
 *
 *   Copyright (C) 2013-2016 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /home/intrepid/src1210_PixHawk2/Firmware/msg/task_stack_info.msg */


#include <px4_config.h>
#include <drivers/drv_orb_dev.h>
#include <microcdr/microCdr.h>
#include <uORB/topics/task_stack_info.h>

constexpr char __orb_task_stack_info_fields[] = "uint64_t timestamp;uint16_t stack_free;uint8_t[16] task_name;uint8_t[6] _padding0;";

ORB_DEFINE(task_stack_info, struct task_stack_info_s, 26,
    __orb_task_stack_info_fields);



void serialize_task_stack_info(const struct task_stack_info_s *input, char *output, uint32_t *length, struct microCDR *microCDRWriter)
{
    if (nullptr == input || nullptr == output || nullptr == length || nullptr == microCDRWriter) return;

    resetStaticMicroCDRForSerialize(microCDRWriter);

	serializeUnsignedShort(input->stack_free, microCDRWriter);
	serializeUnsignedCharArray(input->task_name, 16, microCDRWriter);


    (*length) = microCDRWriter->m_microBuffer->m_serializedBuffer;
}

void deserialize_task_stack_info(struct task_stack_info_s *output, char *input, struct microCDR *microCDRReader)
{
    if (nullptr == output || nullptr == input || nullptr == microCDRReader) return;

    resetStaticMicroCDRForDeserialize(microCDRReader);

	deserializeUnsignedShort(&output->stack_free, microCDRReader);
	deserializeUnsignedChar(&output->task_name[0], microCDRReader);
	deserializeUnsignedChar(&output->task_name[1], microCDRReader);
	deserializeUnsignedChar(&output->task_name[2], microCDRReader);
	deserializeUnsignedChar(&output->task_name[3], microCDRReader);
	deserializeUnsignedChar(&output->task_name[4], microCDRReader);
	deserializeUnsignedChar(&output->task_name[5], microCDRReader);
	deserializeUnsignedChar(&output->task_name[6], microCDRReader);
	deserializeUnsignedChar(&output->task_name[7], microCDRReader);
	deserializeUnsignedChar(&output->task_name[8], microCDRReader);
	deserializeUnsignedChar(&output->task_name[9], microCDRReader);
	deserializeUnsignedChar(&output->task_name[10], microCDRReader);
	deserializeUnsignedChar(&output->task_name[11], microCDRReader);
	deserializeUnsignedChar(&output->task_name[12], microCDRReader);
	deserializeUnsignedChar(&output->task_name[13], microCDRReader);
	deserializeUnsignedChar(&output->task_name[14], microCDRReader);
	deserializeUnsignedChar(&output->task_name[15], microCDRReader);

}